// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysesresults.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createOrUpdateAnalysesResults = `-- name: CreateOrUpdateAnalysesResults :exec
INSERT INTO analyses_results (
results, session_id)
VALUES ( $1, $2)
ON CONFLICT (session_id)
DO UPDATE SET
    results = EXCLUDED.results,
    updated_at = CURRENT_TIMESTAMP
`

type CreateOrUpdateAnalysesResultsParams struct {
	Results   json.RawMessage
	SessionID uuid.UUID
}

func (q *Queries) CreateOrUpdateAnalysesResults(ctx context.Context, arg CreateOrUpdateAnalysesResultsParams) error {
	_, err := q.db.ExecContext(ctx, createOrUpdateAnalysesResults, arg.Results, arg.SessionID)
	return err
}

const getAnalysesResultsBySession = `-- name: GetAnalysesResultsBySession :one
SELECT id, session_id, results, created_at, updated_at FROM analyses_results WHERE session_id=$1
`

func (q *Queries) GetAnalysesResultsBySession(ctx context.Context, sessionID uuid.UUID) (AnalysesResult, error) {
	row := q.db.QueryRowContext(ctx, getAnalysesResultsBySession, sessionID)
	var i AnalysesResult
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Results,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
