// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createContactMessage = `-- name: CreateContactMessage :one
INSERT INTO contact_messages (
first_name, last_name,email,contact_department_id, message )
VALUES ( $1, $2, $3, $4, $5 )
RETURNING id, first_name, last_name, email, contact_department_id, message, created_at
`

type CreateContactMessageParams struct {
	FirstName           string
	LastName            string
	Email               string
	ContactDepartmentID uuid.UUID
	Message             string
}

func (q *Queries) CreateContactMessage(ctx context.Context, arg CreateContactMessageParams) (ContactMessage, error) {
	row := q.db.QueryRowContext(ctx, createContactMessage,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ContactDepartmentID,
		arg.Message,
	)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ContactDepartmentID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getContactDepartments = `-- name: GetContactDepartments :many
SELECT id, name FROM contact_departments
`

func (q *Queries) GetContactDepartments(ctx context.Context) ([]ContactDepartment, error) {
	rows, err := q.db.QueryContext(ctx, getContactDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactDepartment
	for rows.Next() {
		var i ContactDepartment
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailLast24HourContactMessages = `-- name: GetEmailLast24HourContactMessages :one
SELECT COUNT(*)
FROM contact_messages
WHERE email = $1
AND created_at >= NOW() - INTERVAL '24 hours'
`

func (q *Queries) GetEmailLast24HourContactMessages(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEmailLast24HourContactMessages, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEmailLastHourContactMessages = `-- name: GetEmailLastHourContactMessages :one
SELECT COUNT(*)
FROM contact_messages
WHERE email = $1
AND created_at >= NOW() - INTERVAL '1 hour'
`

func (q *Queries) GetEmailLastHourContactMessages(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEmailLastHourContactMessages, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}
