// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createJobPost = `-- name: CreateJobPost :one
INSERT INTO job_posts (
 employer_id, title, description )
VALUES ( $1, $2, $3)
RETURNING id, employer_id, title, description, created_at, updated_at
`

type CreateJobPostParams struct {
	EmployerID  uuid.UUID
	Title       string
	Description string
}

func (q *Queries) CreateJobPost(ctx context.Context, arg CreateJobPostParams) (JobPost, error) {
	row := q.db.QueryRowContext(ctx, createJobPost, arg.EmployerID, arg.Title, arg.Description)
	var i JobPost
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployerJobPosts = `-- name: GetEmployerJobPosts :many
SELECT id, employer_id, title, description, created_at, updated_at FROM job_posts 
WHERE employer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetEmployerJobPosts(ctx context.Context, employerID uuid.UUID) ([]JobPost, error) {
	rows, err := q.db.QueryContext(ctx, getEmployerJobPosts, employerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobPost
	for rows.Next() {
		var i JobPost
		if err := rows.Scan(
			&i.ID,
			&i.EmployerID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobPost = `-- name: GetJobPost :one
SELECT id, employer_id, title, description, created_at, updated_at FROM job_posts 
WHERE id = $1
`

func (q *Queries) GetJobPost(ctx context.Context, id uuid.UUID) (JobPost, error) {
	row := q.db.QueryRowContext(ctx, getJobPost, id)
	var i JobPost
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobPosts = `-- name: GetJobPosts :many
SELECT id, employer_id, title, description, created_at, updated_at FROM job_posts 
ORDER BY created_at DESC
`

func (q *Queries) GetJobPosts(ctx context.Context) ([]JobPost, error) {
	rows, err := q.db.QueryContext(ctx, getJobPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobPost
	for rows.Next() {
		var i JobPost
		if err := rows.Scan(
			&i.ID,
			&i.EmployerID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
