// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AnalysesResult struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	Results   json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EmployerProfile struct {
	ID              uuid.UUID
	CompanyName     string
	CompanyWebsite  string
	CompanySize     int32
	CompanyIndustry string
	UserID          uuid.UUID
}

type JobSeekerProfile struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	ResumeUrl sql.NullString
	UserID    uuid.UUID
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Resume struct {
	ID               uuid.UUID
	OriginalFilename string
	Mime             string
	SizeBytes        int64
	StorageProvider  string
	ObjectKey        string
	StorageUrl       string
	UploadStatus     string
	CreatedAt        time.Time
	SessionID        uuid.UUID
}

type Session struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	Name           string
	UserID         uuid.UUID
	Status         string
	JobTitle       string
	JobDescription string
}

type User struct {
	ID        uuid.UUID
	Email     string
	Role      string
	Password  string
	CreatedAt time.Time
}
