// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AnalysesResult struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	Results   json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EmployerProfile struct {
	ID              uuid.UUID
	CompanyName     string
	CompanyWebsite  string
	CompanySize     int32
	CompanyIndustry string
	UserID          uuid.UUID
}

type JobSeekerProfile struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	ResumeUrl sql.NullString
	UserID    uuid.UUID
}

type Plan struct {
	ID               uuid.UUID
	Name             string
	PlanCode         sql.NullString
	Amount           int32
	Currency         string
	Interval         string
	DailyLimit       int32
	Description      sql.NullString
	SubscriptionPage sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Profession struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Resume struct {
	ID               uuid.UUID
	OriginalFilename string
	Mime             string
	SizeBytes        int64
	StorageProvider  string
	ObjectKey        string
	StorageUrl       string
	UploadStatus     string
	CreatedAt        time.Time
	SessionID        uuid.UUID
}

type Session struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	Name           string
	UserID         uuid.UUID
	Status         string
	JobTitle       string
	JobDescription string
}

type Subscription struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Status          string
	CanceledAt      sql.NullTime
	NextPaymentDate sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PaystackSubCode sql.NullString
	PlanID          uuid.UUID
}

type SubscriptionHistory struct {
	ID             uuid.UUID
	SubscriptionID uuid.UUID
	UserID         uuid.UUID
	EventType      string
	OldValue       sql.NullString
	NewValue       sql.NullString
	EventSource    string
	CreatedAt      time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Role      string
	Password  string
	CreatedAt time.Time
}

type UserDailyUsage struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Count      int32
	MaxDaily   int32
	LastUsedAt time.Time
}

type UserProfession struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ProfessionID uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
