// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plans.sql

package database

import (
	"context"
	"database/sql"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
name, plan_code,amount,currency,daily_limit, description  )
VALUES ( $1, $2, $3,$4,$5,$6 )
RETURNING id, name, plan_code, amount, currency, interval, daily_limit, description, created_at, updated_at
`

type CreatePlanParams struct {
	Name        string
	PlanCode    string
	Amount      int32
	Currency    string
	DailyLimit  int32
	Description sql.NullString
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.Name,
		arg.PlanCode,
		arg.Amount,
		arg.Currency,
		arg.DailyLimit,
		arg.Description,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanCode,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DailyLimit,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlans = `-- name: GetPlans :many
SELECT id, name, plan_code, amount, currency, interval, daily_limit, description, created_at, updated_at FROM plans
`

func (q *Queries) GetPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, getPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlanCode,
			&i.Amount,
			&i.Currency,
			&i.Interval,
			&i.DailyLimit,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
