// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
name,amount,currency,daily_limit, description  )
VALUES ( $1, $2, $3,$4,$5)
RETURNING id, name, plan_code, amount, currency, interval, daily_limit, description, subscription_page, created_at, updated_at
`

type CreatePlanParams struct {
	Name        string
	Amount      int32
	Currency    string
	DailyLimit  int32
	Description sql.NullString
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.DailyLimit,
		arg.Description,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanCode,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DailyLimit,
		&i.Description,
		&i.SubscriptionPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, plan_code, amount, currency, interval, daily_limit, description, subscription_page, created_at, updated_at FROM plans WHERE id=$1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanCode,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DailyLimit,
		&i.Description,
		&i.SubscriptionPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanWithName = `-- name: GetPlanWithName :one
SELECT id, name, plan_code, amount, currency, interval, daily_limit, description, subscription_page, created_at, updated_at FROM plans WHERE name=$1
`

func (q *Queries) GetPlanWithName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanWithName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanCode,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DailyLimit,
		&i.Description,
		&i.SubscriptionPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanWithPlaneCode = `-- name: GetPlanWithPlaneCode :one
SELECT id, name, plan_code, amount, currency, interval, daily_limit, description, subscription_page, created_at, updated_at FROM plans WHERE plan_code=$1
`

func (q *Queries) GetPlanWithPlaneCode(ctx context.Context, planCode sql.NullString) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanWithPlaneCode, planCode)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanCode,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.DailyLimit,
		&i.Description,
		&i.SubscriptionPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlans = `-- name: GetPlans :many
SELECT id, name, plan_code, amount, currency, interval, daily_limit, description, subscription_page, created_at, updated_at FROM plans
`

func (q *Queries) GetPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, getPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlanCode,
			&i.Amount,
			&i.Currency,
			&i.Interval,
			&i.DailyLimit,
			&i.Description,
			&i.SubscriptionPage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePLanSubscriptionPage = `-- name: UpdatePLanSubscriptionPage :exec
UPDATE plans
SET 
  subscription_page = $1
WHERE id = $2
`

type UpdatePLanSubscriptionPageParams struct {
	SubscriptionPage sql.NullString
	ID               uuid.UUID
}

func (q *Queries) UpdatePLanSubscriptionPage(ctx context.Context, arg UpdatePLanSubscriptionPageParams) error {
	_, err := q.db.ExecContext(ctx, updatePLanSubscriptionPage, arg.SubscriptionPage, arg.ID)
	return err
}

const updatePlanCode = `-- name: UpdatePlanCode :exec
UPDATE plans
SET 
  plan_code = $1
WHERE id = $2
`

type UpdatePlanCodeParams struct {
	PlanCode sql.NullString
	ID       uuid.UUID
}

func (q *Queries) UpdatePlanCode(ctx context.Context, arg UpdatePlanCodeParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanCode, arg.PlanCode, arg.ID)
	return err
}

const updatePlanSubscriptionPage = `-- name: UpdatePlanSubscriptionPage :exec
UPDATE plans
SET 
  subscription_page = $1
WHERE id = $2
`

type UpdatePlanSubscriptionPageParams struct {
	SubscriptionPage sql.NullString
	ID               uuid.UUID
}

func (q *Queries) UpdatePlanSubscriptionPage(ctx context.Context, arg UpdatePlanSubscriptionPageParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanSubscriptionPage, arg.SubscriptionPage, arg.ID)
	return err
}
