// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: professions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProfession = `-- name: CreateProfession :one
INSERT INTO professions (
name  )
VALUES ( $1 )
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateProfession(ctx context.Context, name string) (Profession, error) {
	row := q.db.QueryRowContext(ctx, createProfession, name)
	var i Profession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfession = `-- name: CreateUserProfession :one
INSERT INTO user_professions (
user_id, profession_id  )
VALUES ( $1, $2 )
RETURNING id, user_id, profession_id, created_at, updated_at
`

type CreateUserProfessionParams struct {
	UserID       uuid.UUID
	ProfessionID uuid.UUID
}

func (q *Queries) CreateUserProfession(ctx context.Context, arg CreateUserProfessionParams) (UserProfession, error) {
	row := q.db.QueryRowContext(ctx, createUserProfession, arg.UserID, arg.ProfessionID)
	var i UserProfession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserProfession = `-- name: DeleteUserProfession :exec
DELETE FROM user_professions
WHERE user_id = $1 AND profession_id = $2
`

type DeleteUserProfessionParams struct {
	UserID       uuid.UUID
	ProfessionID uuid.UUID
}

func (q *Queries) DeleteUserProfession(ctx context.Context, arg DeleteUserProfessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserProfession, arg.UserID, arg.ProfessionID)
	return err
}

const getProfessions = `-- name: GetProfessions :many
SELECT id, name, created_at, updated_at FROM professions
`

func (q *Queries) GetProfessions(ctx context.Context) ([]Profession, error) {
	rows, err := q.db.QueryContext(ctx, getProfessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profession
	for rows.Next() {
		var i Profession
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfessions = `-- name: GetUserProfessions :many
SELECT id, user_id, profession_id, created_at, updated_at FROM user_professions
WHERE user_id = $1
`

func (q *Queries) GetUserProfessions(ctx context.Context, userID uuid.UUID) ([]UserProfession, error) {
	rows, err := q.db.QueryContext(ctx, getUserProfessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProfession
	for rows.Next() {
		var i UserProfession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProfessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const professionExists = `-- name: ProfessionExists :one
SELECT EXISTS (
    SELECT 1
    FROM professions
    WHERE id = $1
)
`

func (q *Queries) ProfessionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, professionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
