// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resumes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const clearResumes = `-- name: ClearResumes :exec
DELETE  FROM resumes
`

func (q *Queries) ClearResumes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearResumes)
	return err
}

const createResume = `-- name: CreateResume :one
INSERT INTO resumes (session_id, object_key, original_filename, mime, size_bytes, storage_provider, upload_status, storage_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)

RETURNING id, original_filename, mime, size_bytes, storage_provider, object_key, storage_url, upload_status, created_at, session_id
`

type CreateResumeParams struct {
	SessionID        uuid.UUID
	ObjectKey        string
	OriginalFilename string
	Mime             string
	SizeBytes        int64
	StorageProvider  string
	UploadStatus     string
	StorageUrl       string
}

func (q *Queries) CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error) {
	row := q.db.QueryRowContext(ctx, createResume,
		arg.SessionID,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.Mime,
		arg.SizeBytes,
		arg.StorageProvider,
		arg.UploadStatus,
		arg.StorageUrl,
	)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.Mime,
		&i.SizeBytes,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.StorageUrl,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.SessionID,
	)
	return i, err
}

const deleteResumesBySession = `-- name: DeleteResumesBySession :exec
DELETE  FROM resumes WHERE session_id=$1
`

func (q *Queries) DeleteResumesBySession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteResumesBySession, sessionID)
	return err
}

const getResumes = `-- name: GetResumes :one
SELECT id, original_filename, mime, size_bytes, storage_provider, object_key, storage_url, upload_status, created_at, session_id FROM resumes
`

func (q *Queries) GetResumes(ctx context.Context) (Resume, error) {
	row := q.db.QueryRowContext(ctx, getResumes)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.Mime,
		&i.SizeBytes,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.StorageUrl,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.SessionID,
	)
	return i, err
}

const getResumesBySession = `-- name: GetResumesBySession :many
SELECT id, original_filename, mime, size_bytes, storage_provider, object_key, storage_url, upload_status, created_at, session_id FROM resumes WHERE session_id=$1
`

func (q *Queries) GetResumesBySession(ctx context.Context, sessionID uuid.UUID) ([]Resume, error) {
	rows, err := q.db.QueryContext(ctx, getResumesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resume
	for rows.Next() {
		var i Resume
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.Mime,
			&i.SizeBytes,
			&i.StorageProvider,
			&i.ObjectKey,
			&i.StorageUrl,
			&i.UploadStatus,
			&i.CreatedAt,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumeExists = `-- name: ResumeExists :one
SELECT EXISTS (
    SELECT 1
    FROM resumes
    WHERE session_id = $1
)
`

func (q *Queries) ResumeExists(ctx context.Context, sessionID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, resumeExists, sessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateResumeStorageUrlForSession = `-- name: UpdateResumeStorageUrlForSession :exec
UPDATE resumes
SET 
  storage_url = $1,
   object_key=$2,
   original_filename=$3, mime=$4, size_bytes=$5, storage_provider=$6, upload_status=$7 
WHERE session_id = $8
`

type UpdateResumeStorageUrlForSessionParams struct {
	StorageUrl       string
	ObjectKey        string
	OriginalFilename string
	Mime             string
	SizeBytes        int64
	StorageProvider  string
	UploadStatus     string
	SessionID        uuid.UUID
}

func (q *Queries) UpdateResumeStorageUrlForSession(ctx context.Context, arg UpdateResumeStorageUrlForSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateResumeStorageUrlForSession,
		arg.StorageUrl,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.Mime,
		arg.SizeBytes,
		arg.StorageProvider,
		arg.UploadStatus,
		arg.SessionID,
	)
	return err
}
