// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
name, user_id, job_title, job_description )
VALUES ( $1, $2, $3,$4)
RETURNING id, created_at, name, user_id, status, job_title, job_description
`

type CreateSessionParams struct {
	Name           string
	UserID         uuid.UUID
	JobTitle       string
	JobDescription string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Name,
		arg.UserID,
		arg.JobTitle,
		arg.JobDescription,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.JobTitle,
		&i.JobDescription,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, created_at, name, user_id, status, job_title, job_description FROM sessions 
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.UserID,
		&i.Status,
		&i.JobTitle,
		&i.JobDescription,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, created_at, name, user_id, status, job_title, job_description FROM sessions 
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.UserID,
			&i.Status,
			&i.JobTitle,
			&i.JobDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions 
SET status=$1
WHERE id=$2
`

type UpdateSessionStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}
