// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscription_history.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubscriptionHistory = `-- name: CreateSubscriptionHistory :one
INSERT INTO subscription_history (
 user_id, subscription_id,event_type, old_value, new_value, event_source )
VALUES ( $1, $2,$3,$4,$5,$6)
RETURNING id, subscription_id, user_id, event_type, old_value, new_value, event_source, created_at
`

type CreateSubscriptionHistoryParams struct {
	UserID         uuid.UUID
	SubscriptionID uuid.UUID
	EventType      string
	OldValue       sql.NullString
	NewValue       sql.NullString
	EventSource    string
}

func (q *Queries) CreateSubscriptionHistory(ctx context.Context, arg CreateSubscriptionHistoryParams) (SubscriptionHistory, error) {
	row := q.db.QueryRowContext(ctx, createSubscriptionHistory,
		arg.UserID,
		arg.SubscriptionID,
		arg.EventType,
		arg.OldValue,
		arg.NewValue,
		arg.EventSource,
	)
	var i SubscriptionHistory
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.UserID,
		&i.EventType,
		&i.OldValue,
		&i.NewValue,
		&i.EventSource,
		&i.CreatedAt,
	)
	return i, err
}
