// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscriptions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkSubscriptionExist = `-- name: CheckSubscriptionExist :one
SELECT EXISTS(
    SELECT 1 FROM subscriptions WHERE user_id = $1
    )
`

func (q *Queries) CheckSubscriptionExist(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkSubscriptionExist, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
