// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEmployer = `-- name: CreateEmployer :one
INSERT INTO employer_profiles (
user_id, company_name,company_website,company_size,company_industry  )
VALUES ( $1, $2, $3,$4,$5 )
RETURNING id, company_name, company_website, company_size, company_industry, user_id
`

type CreateEmployerParams struct {
	UserID          uuid.UUID
	CompanyName     string
	CompanyWebsite  string
	CompanySize     int32
	CompanyIndustry string
}

func (q *Queries) CreateEmployer(ctx context.Context, arg CreateEmployerParams) (EmployerProfile, error) {
	row := q.db.QueryRowContext(ctx, createEmployer,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyWebsite,
		arg.CompanySize,
		arg.CompanyIndustry,
	)
	var i EmployerProfile
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyWebsite,
		&i.CompanySize,
		&i.CompanyIndustry,
		&i.UserID,
	)
	return i, err
}

const createJobSeeker = `-- name: CreateJobSeeker :one
INSERT INTO job_seeker_profiles (
user_id, first_name,last_name  )
VALUES ( $1, $2, $3)
RETURNING id, first_name, last_name, resume_url, user_id
`

type CreateJobSeekerParams struct {
	UserID    uuid.UUID
	FirstName string
	LastName  string
}

func (q *Queries) CreateJobSeeker(ctx context.Context, arg CreateJobSeekerParams) (JobSeekerProfile, error) {
	row := q.db.QueryRowContext(ctx, createJobSeeker, arg.UserID, arg.FirstName, arg.LastName)
	var i JobSeekerProfile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.ResumeUrl,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
email, role,password  )
VALUES ( $1, $2, $3 )
RETURNING id, email, role, password, created_at
`

type CreateUserParams struct {
	Email    string
	Role     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Role, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id=$1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, role, password, created_at FROM users WHERE $1=id
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithEmail = `-- name: GetUserWithEmail :one
SELECT id, email, role, password, created_at FROM users WHERE $1=email
`

func (q *Queries) GetUserWithEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserWithEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, role, password, created_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET 
  password = $1
WHERE email = $2
`

type UpdatePasswordParams struct {
	Password string
	Email    string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.Email)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email = $1
)
`

func (q *Queries) UserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
