// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_usage.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserUsage = `-- name: GetUserUsage :one
SELECT id, count, last_used_at, max_daily, user_id FROM user_usages WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserUsage(ctx context.Context, userID uuid.UUID) (UserUsage, error) {
	row := q.db.QueryRowContext(ctx, getUserUsage, userID)
	var i UserUsage
	err := row.Scan(
		&i.ID,
		&i.Count,
		&i.LastUsedAt,
		&i.MaxDaily,
		&i.UserID,
	)
	return i, err
}

const insertUserUsage = `-- name: InsertUserUsage :exec
INSERT INTO user_usages (user_id, count, last_used_at, max_daily)
VALUES ($1, 1, NOW(), $2)
ON CONFLICT (user_id) DO UPDATE
SET count = user_usages.count + 1, last_used_at = NOW()
`

type InsertUserUsageParams struct {
	UserID   uuid.UUID
	MaxDaily int32
}

func (q *Queries) InsertUserUsage(ctx context.Context, arg InsertUserUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertUserUsage, arg.UserID, arg.MaxDaily)
	return err
}

const updateUserMaxDaily = `-- name: UpdateUserMaxDaily :exec
UPDATE user_usages
SET max_daily = $1
WHERE user_id = $2
`

type UpdateUserMaxDailyParams struct {
	MaxDaily int32
	UserID   uuid.UUID
}

func (q *Queries) UpdateUserMaxDaily(ctx context.Context, arg UpdateUserMaxDailyParams) error {
	_, err := q.db.ExecContext(ctx, updateUserMaxDaily, arg.MaxDaily, arg.UserID)
	return err
}

const updateUserUsageCount = `-- name: UpdateUserUsageCount :exec
UPDATE user_usages
SET count = $2, last_used_at = NOW()
WHERE user_id = $1
`

type UpdateUserUsageCountParams struct {
	UserID uuid.UUID
	Count  int32
}

func (q *Queries) UpdateUserUsageCount(ctx context.Context, arg UpdateUserUsageCountParams) error {
	_, err := q.db.ExecContext(ctx, updateUserUsageCount, arg.UserID, arg.Count)
	return err
}
