// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_daily_usage.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserUsage = `-- name: GetUserUsage :one
SELECT user_id, count, max_daily, last_used_at FROM user_daily_usages WHERE user_id = $1
`

type GetUserUsageRow struct {
	UserID     uuid.UUID
	Count      int32
	MaxDaily   int32
	LastUsedAt time.Time
}

func (q *Queries) GetUserUsage(ctx context.Context, userID uuid.UUID) (GetUserUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getUserUsage, userID)
	var i GetUserUsageRow
	err := row.Scan(
		&i.UserID,
		&i.Count,
		&i.MaxDaily,
		&i.LastUsedAt,
	)
	return i, err
}

const insertUserUsage = `-- name: InsertUserUsage :exec
INSERT INTO user_daily_usages (user_id, count, max_daily, last_used_at)
VALUES ($1, $2, $3, $4)
`

type InsertUserUsageParams struct {
	UserID     uuid.UUID
	Count      int32
	MaxDaily   int32
	LastUsedAt time.Time
}

func (q *Queries) InsertUserUsage(ctx context.Context, arg InsertUserUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertUserUsage,
		arg.UserID,
		arg.Count,
		arg.MaxDaily,
		arg.LastUsedAt,
	)
	return err
}

const updateUserDailyUsageLimit = `-- name: UpdateUserDailyUsageLimit :exec
INSERT INTO user_daily_usages (user_id, max_daily, count, last_used_at)
VALUES ($1, $2, 0, NOW())
ON CONFLICT (user_id)
DO UPDATE SET max_daily = $2
`

type UpdateUserDailyUsageLimitParams struct {
	UserID   uuid.UUID
	MaxDaily int32
}

func (q *Queries) UpdateUserDailyUsageLimit(ctx context.Context, arg UpdateUserDailyUsageLimitParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDailyUsageLimit, arg.UserID, arg.MaxDaily)
	return err
}

const updateUserUsage = `-- name: UpdateUserUsage :exec
UPDATE user_daily_usages
SET count = $2, last_used_at = $3
WHERE user_id = $1
`

type UpdateUserUsageParams struct {
	UserID     uuid.UUID
	Count      int32
	LastUsedAt time.Time
}

func (q *Queries) UpdateUserUsage(ctx context.Context, arg UpdateUserUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateUserUsage, arg.UserID, arg.Count, arg.LastUsedAt)
	return err
}
